apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: keycloak
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      run: keycloak
  template:
    metadata:
      labels:
        run: keycloak
    spec:
      containers:
        - name: keycloak
          image: ghcr.io/htl-leo-itp-2325-4-5bhitm/drivus-keycloak:latest
          imagePullPolicy: Always
          #command: ["/opt/keycloak/bin/kc.sh", "start-dev", "--proxy", "edge", "--features=declarative-user-profile", "--spi-x509cert-lookup-haproxy-trust-proxy-verification=true"]
          # kubectl port-forward key... 8000:8080 for admin - ui
          command: ["/opt/keycloak/bin/kc.sh", "start-dev", "--proxy", "edge", "--spi-x509cert-lookup-haproxy-trust-proxy-verification=true", "--hostname-admin-url=http://localhost:8000", "--log-level=INFO" ]

          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              httpHeaders:
                - name: Accept
                  value: application/json
              path: /health/ready
              port: http
            initialDelaySeconds: 60
          livenessProbe:
            httpGet:
              httpHeaders:
                - name: Accept
                  value: application/json
              path: health/live
              port: http
            initialDelaySeconds: 180
          env:
            - name: KEYCLOAK_ADMIN
              #           value: administrator
              valueFrom:
                secretKeyRef:
                  name: keycloak-credentials
                  key: adminusername
            - name: KEYCLOAK_ADMIN_PASSWORD
              #           value: password
              valueFrom:
                secretKeyRef:
                  name: keycloak-credentials
                  key: adminpassword
            - name: KC_DB
              value: postgres
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-credentials
                  key: dbuser
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-credentials
                  key: dbpassword
            - name: KC_DB_URL_HOST
              value: postgres
            - name: KC_DB_URL_DATABASE
              value: keycloak

            - name: KC_HOSTNAME_URL
              # change the external URL to https://your.server.com
              value: https://it200267.cloud.htl-leonding.ac.at
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "false"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_HTTP_PORT
              value: "8080"
            - name: KC_LOG_LEVEL
              value: INFO
            - name: keycloak.profile.feature.upload_scripts
              value: enabled
            - name: KC_HEALTH_ENABLED
              value: "true"