name: GitHub Actions Demo
run-name: ${{ github.actor }} Building maven project
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v4
      - run: ls -l backend
      - uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '21'
      - run: java -version
      - run: |
          mvn -B package
      