# docker compose file for our standalone postgres database
services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    environment:
      - POSTGRES_PASSWORD=demo
      - POSTGRES_USER=demo
      - POSTGRES_DB=demo
    healthcheck:
          test: pg_isready --dbname=keycloak --username=keycloak
          interval: 40s
          timeout: 30s
          retries: 3
          start_period: 10s
volumes:
  postgres: