###
POST http://localhost:4200/api/drivus/users/postUser
Content-Type: application/json

{
  "firstName": "Max",
  "lastName": "Muster",
  "emailAddress": "test@gmail.com",
  "phoneNr": "1133676",
  "username": "maxii"
}

###

POST http://localhost:8080/api/drivus/users/newProfilePicture
Content-Type: application/json

{
"username": "janine",
"img": "2"
}

###

POST http://localhost:8080/api/drivus/rides/rating
Content-Type: application/json

{
"id": 4,
"stars": 5
}